name: altech_ui_flutter_example
description: Example app for altech_ui_flutter.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  altech_ui_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
