name: altech_ui_flutter
description: Modern, reusable, and customizable Flutter UI component library with Material 3, design tokens, and centralized theming.
version: 2.0.1
homepage: https://github.com/Luxxn12/altech_ui_flutter
repository: https://github.com/Luxxn12/altech_ui_flutter
issue_tracker: https://github.com/Luxxn12/altech_ui_flutter/issues
documentation: https://github.com/Luxxn12/altech_ui_flutter#readme
topics:
  - flutter-ui
  - material3
  - design-system
  - ui-components
  - flutter-package

environment:
  sdk: ^3.9.0
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:
